### ISSUE TITLE
Remove defaults channel from environment yaml file

### ISSUE THREAD

**Issue by matthew-mizielinski** [CMIP-Data-Request/CMIP7_DReq_Software#10]
Following the [Anaconda licensing](https://www.anaconda.com/pricing/terms-of-service-faqs) changes some time ago the defaults channel is something we should drop -- This is a fairly hot topic in several institutions, with some looking to block the use of any channel which would lead them open to incurring substantial licencing costs.

**Comment by JamesAnstey** [comment]
Thanks for catching this @matthew-mizielinski. The env I made with `env.yml` has no packages from `defaults` channel, only `conda-forge`, so there was no need for `defaults` to be in there. I've removed `defaults` from `env.yml` on the `main` branch.
