### ISSUE TITLE
Example script fails

### ISSUE THREAD

**Issue by jesusff** [CMIP-Data-Request/CMIP7_DReq_Software#15]
The example script fails (apart from #14 ) with:
```
$ python workflow_example.py 
Loading version v1.0beta'.
Traceback (most recent call last):
  File "/home/chus/zzgit/CMIP-Data-Request/CMIP7_DReq_Software/scripts/workflow_example.py", line 51, in <module>
    expt_vars = dq.get_requested_variables(content, use_opps, max_priority='Low')
  File "/home/chus/zzgit/CMIP-Data-Request/CMIP7_DReq_Software/scripts/../sandbox/JA/dreq_query.py", line 73, in get_requested_variables
    tables = content[base_name]
             ~~~~~~~^^^^^^^^^^^
KeyError: 'Data Request v1.0beta'
```
It seems that, regardless of the version, the `base_name` is always `"Data Request"`. I managed to go through the example by changing here:

https://github.com/CMIP-Data-Request/CMIP7_DReq_Software/blob/da778dcd7549b7cd782f569f13c13da45c0fcd1b/sandbox/JA/dreq_query.py#L36-L37

```diff
 def version_base_name():
-    return f'Data Request {DREQ_VERSION}'
+    return f'Data Request'
```

**Comment by sol1105** [comment]
Thank you for reporting this. In a recent PR a consolidation function was added that shall get the dictionary in a consistent format whether the information comes from the "raw" or the "release" airtable export json file. I maybe overdid it a bit by also removing the data request version from the dictionary key. We can discuss if that makes sense or not.

The old behaviour can be achieved by:
```
dreq = dc.load(version, consolidate=False)
```

**Comment by jesusff** [comment]
Thank you. That worked 🙂
